### ISSUE TITLE
Can't locate object method "is_done" via package "Promises::Deferred"

### ISSUE THREAD

**Issue by eserte** [sysread/Promises-Channel#5]
On some of my smokers the test suite fails:
```
Can't locate object method "is_done" via package "Promises::Deferred" at (eval 96) line 17.
	(in cleanup) Can't locate object method "is_done" via package "Promises::Deferred" at (eval 96) line 17.
# Seeded srand with seed '20190617' from local date.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 255 just after 4.
t/basics.t ............. 
Dubious, test returned 255 (wstat 65280, 0xff00)
All 4 subtests passed 
```

Maybe this happens if Promises.pm is too old --- 0.99 and newer seems to be fine.

**Comment by sysread** [comment]
Thank you for the report. I've updated the minimum version of `Promises` to `0.96`, which is the first stable version to include `is_done`. This is fixed in [8327e7d8a5fb466457144db0d2373164fc84675e](https://github.com/sysread/Promises-Channel/commit/8327e7d8a5fb466457144db0d2373164fc84675e)
